ScamSearcher/urls.py
"""ROOT_URLCONF for ScamSearcher project."""
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from ScamSearcher.views import login, logout, welcome, user_profile, \
                               password_changed
from website_management.views import website_dashboard


urlpatterns = (
    url(r'^$', website_dashboard, name='welcome'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login$', login, name='login'),
    url(r'^logout$', logout, name='logout'),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^password_change/',
        auth_views.password_change,
        {'post_change_redirect': 'password_changed'},
        name='password_change'),
    url(r'^password_changed/$',
        password_changed,
        name='password_changed'),
    url(r'^$', welcome, name='welcome'),
    url(r'^profile/$', user_profile, name='user_profile'),

    url(r'^website_management/',
        include('website_management.urls',
                namespace='website_management',
                app_name='website_management')),
    url(r'^website_analyzer/',
        include('website_analyzer.urls',
                namespace='website_analyzer',
                app_name='website_analyzer')),
    url(r'^administrative/',
        include('administrative.urls',
                namespace='administrative',
                app_name='administrative')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

administrative/urls.py
"""urls module for adminstrative app."""
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views


urlpatterns = [
    url(r'^$', views.admin_dashboard, name='admin_dashboard'),
    # client url section
    url(r'^add-client/$',
        views.add_client, name='add_client'),
    url(r'^view-client/$',
        views.view_client, name='view_client'),
    url(r'^edit-client/(?P<pk>\d+)/$',
        login_required(views.EditClient.as_view()), name='edit_client'),
    url(r'^delete-client/(?P<client_id>\d+)/$',
        views.delete_client, name='delete_client'),
    url(r'^delete-client-process/$',
        views.delete_client_process, name='delete_client_process'),
    url(r'^detail-client/(?P<client_id>\d+)/$',
        views.detail_client, name='detail_client'),
    url(r'^add-homepage/(?P<client_id>\d+)/$',
        views.add_homepage, name='add_homepage'),
    url(r'^delete-homepage/(?P<pk>\d+)/$',
        login_required(views.WebsiteDelete.as_view()),
        name='delete_homepage'),
    url(r'^delete-homepage-success/$',
        views.delete_homepage_success,
        name='delete_client_website_success'),
    url(r'^view-event/(?P<client_id>\d+)/$',
        views.view_event, name='view_event'),
    url(r'^add-event/(?P<client_id>\d+)/$',
        views.add_event, name='add_event'),
    url(r'^edit-event/(?P<pk>\d+)/$',
        login_required(views.EditEvent.as_view()),
        name='edit_event'),
    url(r'^delete-event/(?P<event_id>\d+)/$',
        views.delete_event, name='delete_event'),
    url(r'^delete-event-process/$',
        views.delete_event_process, name='delete_event_process'),
    url(r'^detail-event/(?P<event_id>\d+)/$',
        views.detail_event, name='detail_event'),
    url(r'^view-client-keyword/(?P<client_id>\d+)/$',
        views.view_client_keyword, name='view_client_keyword'),
    url(r'^add-client-keyword/(?P<client_id>\d+)/$',
        views.add_client_keyword, name='add_client_keyword'),
    url(r'^view-client-sequence/(?P<client_id>\d+)/$',
        views.view_client_sequence, name='view_client_sequence'),
    url(r'^add-client-sequence/(?P<client_id>\d+)/$',
        views.add_client_sequence, name='add_client_sequence'),

    # operator url section
    url(r'^add-operator/(?P<client_id>\d+)/$',
        views.add_operator, name='add_operator'),
    url(r'^view-operator/(?P<client_id>\d+)/$',
        views.view_operator, name='view_operator'),
    url(r'^edit-operator/(?P<operator_id>\d+)/$',
        views.edit_operator, name='edit_operator'),
    url(r'^edit-operator-process/$',
        views.edit_operator_process, name='edit_operator_process'),
    url(r'^delete-operator/(?P<operator_id>\d+)/$',
        views.delete_operator, name='delete_operator'),
    url(r'^delete-operator-process/$',
        views.delete_operator_process, name='delete_operator_process'),

    # user url section
    url(r'^add-user/$', views.add_user, name='add_user'),
    url(r'^view-user/$',
        views.view_user, name='view_user'),
    url(r'^edit-user/(?P<pk>\d+)/$',
        login_required(views.EditUser.as_view()),
        name='edit_user'),
    url(r'^delete-user/(?P<pk>\d+)/$',
        login_required(views.DeleteUser.as_view()),
        name='delete_user'),

    # event url section
    url(r'^view-all-event/$',
        views.view_all_event, name='view_all_event'),
    url(r'^view-sent-mail/$',
        views.view_sent_mail,
        name='view_sent_mail'),
    ]

website_analyzer/urls.py
"""urls module for website_analyzer app."""
from django.conf.urls import url

from website_analyzer import views


urlpatterns = [
    url(r'^$', views.analyst_dashboard,
        name='analyst_dashboard'),
    url(r'^analyze_website/(?P<hp_id>\d+)/$',
        views.analyze_website, name='analyze_website'),
    url(r'^start_analyze/(?P<hp_id>\d+)/$',
        views.start_analyze, name='start_analyze'),
    url(r'^extract_links/(?P<web_id>\d+)/$',
        views.extract_links, name='extract_links'),
    url(r'^add_scam_website/$', views.add_scam_website,
        name='add_scam_website'),
    url(r'^view_websites/$', views.view_websites,
        name='view_websites'),
    url(r'^view_sequence/$', views.view_sequence,
        name='view_sequence'),
    url(r'^add_sequence/$', views.add_sequence,
        name='add_sequence'),
    url(r'^crawl_website/(?P<homepage_id>\d+)/$',
        views.crawl_homepage,
        name='crawl_website'),
    url(r'^start_sequence_analysist/(?P<homepage_id>\d+)$',
        views.start_sequence_analysist,
        name='start_sequence_analysist'),
    url(r'^view_analyst_result$', views.view_analyst_result,
        name='view_analyst_result'),
    url(r'^view_analyst_domains/$',
        views.view_analyst_domains,
        name='view_analyst_domains'),
    url(r'^edit_analyst_domain/(?P<dom_id>\d+)/$',
        views.edit_analyst_domain,
        name='edit_analyst_domain'),
    url(r'^detail_analyst_domain/(?P<dom_id>\d+)/$',
        views.detail_analyst_domain,
        name='detail_analyst_domain'),
    ]

website_management/urls.py
"""urls module for website_management app."""
from django.conf.urls import url

from website_management import views


urlpatterns = [
    url(r'^$', views.website_dashboard,
        name='website_dashboard'),
    url(r'^homepage_detail/(?P<hp_id>\d+)/$',
        views.homepage_detail, name='homepage_detail'),
    url(r'^view_all_homepages/$',
        views.view_all_homepages, name='view_all_homepages'),
    url(r'^view_all_keywords/$',
        views.view_all_keywords, name='view_all_keywords'),
]

ScamSearcher/forms.py
"""forms module for main ScamSearcher project."""
from django import forms


class LoginForm(forms.Form):
    """Generate login forms."""
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

ScamSearcher/views.py
"""views module for ScamSearcher project."""
from django.contrib.auth import authenticate, login as auth_login, \
                                logout as auth_logout
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from ScamSearcher.forms import LoginForm


@login_required(login_url='login')
def welcome(request):
    "display welcome page"
    return render(request, "welcome.html")


def login(request):
    "display login form"
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    auth_login(request, user)
                    return redirect('welcome')
                else:
                    return redirect('logout')
            else:
                return redirect('logout')
    else:
        form = LoginForm()
    return render(request,
                  'login.html',
                  {'form': form})


def logout(request):
    "log user out"
    auth_logout(request)
    return redirect('login')


@login_required
def user_profile(request):
    "display user's profile"
    return render(request, 'profile.html')


@login_required
def password_changed(request):
    "display password successfully chenged"
    return render(request, 'password_changed.html')

ScamSearcher/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <title>{% block pagetitle %}Scam Searcher{% endblock %}</title>
    <meta http-equiv="Content-Type"
        content="application/xhtml+xml; charset=utf-8" />
    <meta name="description"
        content="Automatically search and monitor internet for scam." />
    <meta name="keywords"
        content="Automatically search and monitor internet for scam." />
    <meta name="robots" content="index, follow" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <!-- Bootstrap -->
    <link rel="stylesheet"
        type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>
</head>
<body>
<div class="container" >
    <div class="row page-header">
        <h1>SCAM SEARCHER</h1>
        <h2>Search for scam website, automatically</h2>
        <ul class="nav nav-tabs">
        {% block mainmenu %}
            <li>
                <a href="{% url 'website_management:website_dashboard' %}">
                    Website
                </a>
            </li>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'website_analyzer:analyst_dashboard' %}">
                    Analyst
                </a>
            </li>
            <li>
                <a href="{% url 'administrative:admin_dashboard' %}">
                    Administrative
                </a>
            </li>
                <li>
                    <a href="{% url 'user_profile' %}">
                        {{ user.get_username }}
                    </a>
                </li>
                <li>
                    <a href="{% url 'logout' %}">
                        Logout
                    </a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'login' %}">
                        Login
                    </a>
                </li>
            {% endif %}
        {% endblock %}
        </ul>
    </div>
    <div class="row">
        <div class="col-sm-4 panel">
            {% block navigation %} {% endblock %}
            {% block subnavigation %} {% endblock %}
        </div>
        <div class="col-sm-8 panel">
            <!-- Column 1 start -->
                <div class="panel panel-info">
                    <div class="panel-heading">
                        {% block content-heading %} {% endblock %}
                    </div>
                    <div class="panel-body">
                        {% block content-body %} {% endblock %}
                    </div>
                </div>
            <!-- Column 1 end -->
        </div>
    </div>
    <div class="row panel panel-footer">
        <div style="float:left;margin:5px;">
            <a href="https://github.com/essanpupil" target="_blank">
                github.com/essanpupil
            </a>
        </div>
        <div style="float:left;margin:5px;">
            <a href="https://www.facebook.com/essanpupil" target="_blank">
                facebook.com/esssanpupil
            </a>
        </div>
        <div style="float:left;margin:5px;">
            <a href="https://twitter.com/essanpupil" target="_blank">
                twitter.com/essanpupil
            </a>
        </div>
        <div style="float:left;margin:5px;">
            <a href="http://id.linkedin.com/in/essanpupil" target="_blank">
                linkedin.com/essanpupil
            </a>
        </div>
        <div style="float:left;margin:5px;">
            Copyright pupil 2015
        </div>
    </div>
<div>
</body>
</html>

ScamSearcher/templates/password_changed.html
{% extends "base.html" %}

{% block content %}
<h4>Password diubah</h4>
Perubahan password sukses dilakukan
{% endblock %}

ScamSearcher/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h4>Profile user:{{ user.username }}</h4>
<table>
<tr><th>Username</th><td>{{ user.get_username }}</td></tr>
<tr><th>Nama lengkap</th><td>{{ user.get_full_name }}</td></tr>
<tr><th>Email</th><td>{{ user.email }}</td></tr>
<tr><th>Apakah user ini termasuk staff?</th><td>{{ user.is_staff|yesno:"ya,tidak" }}</td></tr>
<tr><th>Apakah user ini termasuk superuser</th><td>{{ user.is_superuser|yesno:"Ya,tidak" }}</td></tr>
<tr><th>Tindakan</th><td><a href="{% url 'password_change' %}">Ubah password</a></td></tr>
</table>
{% endblock %}

ScamSearcher/templates/welcome.html
{% extends 'base.html' %}
{% block navigation %}
{% endblock %}
{% block content %}
<h4>Selamat datang {{ user.username }}</h4>
Selamat datang di Scam Searcher
{% endblock %}