ScamSearcher/urls.py
"""ROOT_URLCONF for ScamSearcher project."""
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from ScamSearcher.views import login, logout, welcome, user_profile, \
                               password_changed
from website_management.views import website_dashboard


urlpatterns = (
    url(r'^$', website_dashboard, name='welcome'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login$', login, name='login'),
    url(r'^logout$', logout, name='logout'),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^password_change/',
        auth_views.password_change,
        {'post_change_redirect': 'password_changed'},
        name='password_change'),
    url(r'^password_changed/$',
        password_changed,
        name='password_changed'),
    url(r'^$', welcome, name='welcome'),
    url(r'^profile/$', user_profile, name='user_profile'),

    url(r'^website_management/',
        include('website_management.urls',
                namespace='website_management',
                app_name='website_management')),
    url(r'^website_analyzer/',
        include('website_analyzer.urls',
                namespace='website_analyzer',
                app_name='website_analyzer')),
    url(r'^administrative/',
        include('administrative.urls',
                namespace='administrative',
                app_name='administrative')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

website_analyzer/urls.py
"""urls module for website_analyzer app."""
from django.conf.urls import url

from website_analyzer import views


urlpatterns = [
    url(r'^$', views.analyst_dashboard,
        name='analyst_dashboard'),
    url(r'^analyze_website/(?P<hp_id>\d+)/$',
        views.analyze_website, name='analyze_website'),
    url(r'^start_analyze/(?P<hp_id>\d+)/$',
        views.start_analyze, name='start_analyze'),
    url(r'^extract_links/(?P<web_id>\d+)/$',
        views.extract_links, name='extract_links'),
    url(r'^add_scam_website/$', views.add_scam_website,
        name='add_scam_website'),
    url(r'^view_websites/$', views.view_websites,
        name='view_websites'),
    url(r'^view_sequence/$', views.view_sequence,
        name='view_sequence'),
    url(r'^add_sequence/$', views.add_sequence,
        name='add_sequence'),
    url(r'^crawl_website/(?P<homepage_id>\d+)/$',
        views.crawl_homepage,
        name='crawl_website'),
    url(r'^start_sequence_analysist/(?P<homepage_id>\d+)$',
        views.start_sequence_analysist,
        name='start_sequence_analysist'),
    url(r'^view_analyst_result$', views.view_analyst_result,
        name='view_analyst_result'),
    url(r'^view_analyst_domains/$',
        views.view_analyst_domains,
        name='view_analyst_domains'),
    url(r'^edit_analyst_domain/(?P<dom_id>\d+)/$',
        views.edit_analyst_domain,
        name='edit_analyst_domain'),
    url(r'^detail_analyst_domain/(?P<dom_id>\d+)/$',
        views.detail_analyst_domain,
        name='detail_analyst_domain'),
    ]

website_management/urls.py
"""urls module for website_management app."""
from django.conf.urls import url

from website_management import views


urlpatterns = [
    url(r'^$', views.website_dashboard,
        name='website_dashboard'),
    url(r'^homepage_detail/(?P<hp_id>\d+)/$',
        views.homepage_detail, name='homepage_detail'),
    url(r'^view_all_homepages/$',
        views.view_all_homepages, name='view_all_homepages'),
    url(r'^view_all_keywords/$',
        views.view_all_keywords, name='view_all_keywords'),
]

website_management/models.py
"""models module for website_management app."""
from django.db import models


class Domain(models.Model):
    """Store webpages domain"""
    name = models.CharField(unique=True, max_length=75)
    date_added = models.DateField(auto_now=True)

    def __str__(self):
        return self.name


class Website(models.Model):
    """Store homepages of webpages"""
    name = models.CharField(max_length=100, unique=True)
    domain = models.ForeignKey(Domain, blank=True, null=True)
    date_added = models.DateField(auto_now=True)
    crawl_completed = models.BooleanField(default=False)
    times_analyzed = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Webpage(models.Model):
    """Store webpages"""
    url = models.URLField(max_length=255, unique=True)
    full_url = models.TextField(blank=True, default="")
    homepage = models.ForeignKey(Website, blank=True, null=True)
    html_page = models.TextField(blank=True)
    date_added = models.DateField(auto_now=True)
    last_response = models.CharField(max_length=3, blank=True)
    last_response_check = models.DateField(blank=True, null=True)
    redirect_url = models.URLField(blank=True)
    times_crawled = models.IntegerField(default=0)

    def __str__(self):
        return self.url

website_management/forms.py
from django.forms import ModelForm
from django import forms

from website_management.models import Webpage
from website_analyzer.models import SearchKeywords

class AddWebpageForm(ModelForm):
    """input new webpage url"""
    class Meta:
        model = Webpage
        fields = ['url']


class SearchWebpageForm(forms.Form):
    """form to manually search webpage"""
    keyword = forms.CharField(label='keyword', max_length=255)
    page = forms.IntegerField(label='page', initial=1)


class AddNewKeywordForm(ModelForm):
    "Form to add new search keyword, which is saved in model Query"
    class Meta:
        model = SearchKeywords
        fields = ['keywords']

website_management/views.py
"""views module to manage website data."""
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from website_management.models import Website
from website_analyzer.models import SearchKeywords


def website_dashboard(request):
    """display info summary about saved webpages, homepage, & domain"""
    homepages = Website.objects.all()
    context = {'homepage_count': homepages.count(),
               'newest_5_homepage': []}
    for homepage in homepages.order_by('id').reverse()[0:5]:
        context['newest_5_homepage'].append(
            {'name': homepage.name, 'id': homepage.id})
    return render(request, 'website_management/dashboard.html', context)


def homepage_detail(request, hp_id):
    "display detail info of selected homepage"
    homepage = get_object_or_404(Website, id=hp_id)
    context = {
        'hpname': homepage.name,
        'hpid': homepage.id,
        'hpadded': homepage.date_added,
        'hpdomain': homepage.domain.name,
        'iddom': homepage.domain.id,
        'hpweb': []
    }
    for item in homepage.webpage_set.all():
        context['hpweb'].append({'url': item.url, 'id': item.id})
    return render(request, 'website_management/homepage_detail.html', context)


def view_all_homepages(request):
    """display all webpage"""
    homes = Website.objects.all().order_by('id').reverse()
    context = {'homes': []}
    for item in homes:
        context['homes'].append({
            'name': item.name,
            'date_added': item.date_added,
            'domain': item.domain,
            'id': item.id})
    paginator = Paginator(context['homes'], 10)
    page = request.GET.get('page')
    try:
        context['homes'] = paginator.page(page)
    except PageNotAnInteger:
        context['homes'] = paginator.page(1)
    except EmptyPage:
        context['homes'] = paginator.page(paginator.num_pages)
    return render(request,
                  'website_management/view_all_homepages.html', context)


def view_all_keywords(request):
    """display all keywords"""
    queries = SearchKeywords.objects.all().order_by('id').reverse()
    context = {'queries': []}
    for item in queries:
        context['queries'].append({'keyword': item.keywords,
                                   'date_added': item.date_added,
                                   'times_used': item.times_used,
                                   'id': item.id})
    return render(request,
                  'website_management/view_all_keywords.html', context)

website_management/templates/website_management/base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-GB">
<head>
    <title>{% block pagetitle %}Scam Searcher{% endblock %}</title>
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
    <meta name="description" content="Automatically search and monitor internet for scam." />
    <meta name="keywords" content="Automatically search and monitor internet for scam." />
    <meta name="robots" content="index, follow" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="{% static 'website_management/screen.css' %}" media="screen" />
</head>
<body>

<div id="header">
    <h1>SCAM SEARCHER</h1>
    <h2>Search for scam website, automatically</h2>
    <ul>
    {% block mainmenu %}
    {% endblock %}
    </ul>
</div>
<div class="colmask leftmenu">
    <div class="colleft">
        <div class="col1">
            <!-- Column 1 start -->
            {% block content %} {% endblock %}
            <!-- Column 1 end -->
        </div>
        <div class="col2">
            <!-- Column 2 start -->
            {% block navigation %} {% endblock %}
            {% block subnavigation %} {% endblock %}
            <!-- Column 2 end -->
        </div>
    </div>
</div>
<div id="footer">
    <a href="https://github.com/essanpupil" target="_blank">github.com/essanpupil</a><br />
    <a href="https://www.facebook.com/essanpupil" target="_blank">facebook.com/esssanpupil</a><br />
    <a href="https://twitter.com/essanpupil" target="_blank">twitter.com/essanpupil</a><br />
    <a href="http://id.linkedin.com/in/essanpupil" target="_blank">linkedin.com/essanpupil</a><br />
    Copyright pupil 2015
</div>
</body>
</html>

website_management/templates/website_management/dashboard.html
{% extends 'base.html' %}
{% block pagetitle %}
Welcome to ScamSearcher Project {% if user.is_authenticated %}{{ user.username }}{% endif %}
{% endblock %}
{% block navigation %}
    {% include 'website_management/website_nav.html' %}
{% endblock %}
{% block content-heading %}Summary information{% endblock %}
{% block content-body %}
    <table class="table table-bordered table-condensed">
        <tr>
            <th align="left">Total websites</th><td>{{ hp_count }}</td>
        </tr>
    </table>
    <table class="table table-bordered table-condensed">
        <tr><th>Latest added websites</th></tr>
        {% for hp in newest_5_hp %}
        <tr>
            <td>
                <a href="{% url 'website_management:homepage_detail' hp.id %}">
                    {{ hp.name }}
                </a>
            </td>
        </tr>
        {% empty %}
        <tr><td>Homepage database empty</td></tr>
        {% endfor %}
    </table>
{% endblock %}

website_management/templates/website_management/homepage_detail.html
{% extends 'base.html' %}
{% block navigation %}
    {% include 'website_management/website_nav.html' %}
{% endblock %}
{% block content-heading %}Website detail{% endblock %}
{% block content-body %}
    <table class="table table-bordered">
        <tr>
            <th align="left">Homepage Name</th>
            <td>
                    {{ hpname }}
            </td>
        </tr>
        <tr>
            <th align="left">Date Added</th>
            <td>{{ hpadded }}</td>
        </tr>
        <tr>
            <th align="left">Free Domain</th>
            <td>{{ is_free_domain }}</td>
        </tr>
        <tr>
            <th align="left">Site Status</th>
            <td>{{ site_status }}</td>
        </tr>
        <tr>
            <th align="left">Scam Status</th>
            <td>{{ scam_status }}</td>
        </tr>
    </table>
{% endblock %}

website_management/templates/website_management/homepage_detail_nav.html
<div class="panel panel-primary">
    <div class="panel-heading">Homepage detail navigation</div>
    <div class="panel-body">
        <ul class="list-group">
            <li class="list-group-item">
                <a href="{% url 'website_analyzer:analyze_website' hpid %}">
                    Analyze website
                </a>
            </li>
        </ul>
    </div>
</div>

website_management/templates/website_management/view_all_homepages.html
{% extends 'base.html' %}
{% block pagetitle %}View all websites{% endblock %}
{% block navigation %}
    {% include 'website_management/website_nav.html' %}
    <div class="pagination">
        <span class="step-links">
            {% if websites.has_previous %}
                <a href="?page={{ homes.previous_page_number }}">previous</a>
            {% endif %}
            <span class="current">
                Page {{ homes.number }} of {{ homes.paginator.num_pages }}.
            </span>
            {% if homes.has_next %}
                <a href="?page={{ homes.next_page_number }}">next</a>
            {% endif %}
        </span>
</div>
{% endblock %}
{% block content-heading %}<h3>View all websites</h3>{% endblock %}
{% block content-body %}
    {{ error_message }}
    <table id="table_websites" class="table table-bordered table-condensed">
        <tr>
            <th>No.</th>
            <th>Websites</th>
            <th>Scam status</th>
            <th>Site status</th>
            <th>Action</th>
        </tr>
        {% for hp in homes %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ hp.name }}</td>
                <td>{{ hp.scam_status }}</td>
                <td>{{ hp.site_status }}</td>
                <td>
                    <a href="{% url 'website_management:homepage_detail' hp.id %}">
                        Detail
                    </a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

website_management/templates/website_management/view_all_keywords.html
{% extends "base.html" %}
{% block pagetitle %}View all keywords{% endblock %}
{% block navigation %}
    {% include "website_management/website_nav.html" %}
{% endblock %}
{% block content-heading %}<h3>View all keywords</h3>{% endblock %}
{% block content-body %}
    {{ error_message }}
    <table id="table_keywords" class="table table-bordered table-condensed">
        <tr>
            <th>No.</th>
            <th>Keyword</th>
            <th>Times Used</th>
            <th>Date Added</th>
        </tr>
        {% for query in queries %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ query.keyword }}</td>
                <td>{{ query.times_used }}</td>
                <td>{{ query.date_added }}</td>
            </tr>
        {% empty %}
            <tr>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

website_management/templates/website_management/website_nav.html
<div class="panel panel-primary">
    <div class="panel-heading">
        Website management navigation
    </div>
    <div class="panel-body">
        <ul class="list-group">
            <li class="list-group-item">
                <a href="{% url 'website_management:view_all_keywords' %}">
                    View all keywords
                </a>
            </li>
            <li class="list-group-item">
                <a href="{% url 'website_management:view_all_homepages' %}">
                    View all websites
                </a>
            </li>
        </ul>
    </div>
</div>