ScamSearcher/urls.py
"""ROOT_URLCONF for ScamSearcher project."""
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from ScamSearcher.views import login, logout, welcome, user_profile, \
                               password_changed
from website_management.views import website_dashboard


urlpatterns = (
    url(r'^$', website_dashboard, name='welcome'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login$', login, name='login'),
    url(r'^logout$', logout, name='logout'),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^password_change/',
        auth_views.password_change,
        {'post_change_redirect': 'password_changed'},
        name='password_change'),
    url(r'^password_changed/$',
        password_changed,
        name='password_changed'),
    url(r'^$', welcome, name='welcome'),
    url(r'^profile/$', user_profile, name='user_profile'),

    url(r'^website_management/',
        include('website_management.urls',
                namespace='website_management',
                app_name='website_management')),
    url(r'^website_analyzer/',
        include('website_analyzer.urls',
                namespace='website_analyzer',
                app_name='website_analyzer')),
    url(r'^administrative/',
        include('administrative.urls',
                namespace='administrative',
                app_name='administrative')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

website_analyzer/urls.py
"""urls module for website_analyzer app."""
from django.conf.urls import url

from website_analyzer import views


urlpatterns = [
    url(r'^$', views.analyst_dashboard,
        name='analyst_dashboard'),
    url(r'^analyze_website/(?P<hp_id>\d+)/$',
        views.analyze_website, name='analyze_website'),
    url(r'^start_analyze/(?P<hp_id>\d+)/$',
        views.start_analyze, name='start_analyze'),
    url(r'^extract_links/(?P<web_id>\d+)/$',
        views.extract_links, name='extract_links'),
    url(r'^add_scam_website/$', views.add_scam_website,
        name='add_scam_website'),
    url(r'^view_websites/$', views.view_websites,
        name='view_websites'),
    url(r'^view_sequence/$', views.view_sequence,
        name='view_sequence'),
    url(r'^add_sequence/$', views.add_sequence,
        name='add_sequence'),
    url(r'^crawl_website/(?P<homepage_id>\d+)/$',
        views.crawl_homepage,
        name='crawl_website'),
    url(r'^start_sequence_analysist/(?P<homepage_id>\d+)$',
        views.start_sequence_analysist,
        name='start_sequence_analysist'),
    url(r'^view_analyst_result$', views.view_analyst_result,
        name='view_analyst_result'),
    url(r'^view_analyst_domains/$',
        views.view_analyst_domains,
        name='view_analyst_domains'),
    url(r'^edit_analyst_domain/(?P<dom_id>\d+)/$',
        views.edit_analyst_domain,
        name='edit_analyst_domain'),
    url(r'^detail_analyst_domain/(?P<dom_id>\d+)/$',
        views.detail_analyst_domain,
        name='detail_analyst_domain'),
    ]

website_management/urls.py
"""urls module for website_management app."""
from django.conf.urls import url

from website_management import views


urlpatterns = [
    url(r'^$', views.website_dashboard,
        name='website_dashboard'),
    url(r'^homepage_detail/(?P<hp_id>\d+)/$',
        views.homepage_detail, name='homepage_detail'),
    url(r'^view_all_homepages/$',
        views.view_all_homepages, name='view_all_homepages'),
    url(r'^view_all_keywords/$',
        views.view_all_keywords, name='view_all_keywords'),
]

website_analyzer/forms.py
"""forms module for website_analyzer app."""
from django.forms import ModelForm
from django import forms

from website_management.models import Webpage
from website_analyzer.models import StringParameter, ExtendWebsite, \
                                    ExtendDomain


class AddScamWebsiteForm(ModelForm):
    """add known scam website to database"""
    class Meta:  # lint:ok
        model = Webpage
        fields = ['url']


class AddSequenceForm(ModelForm):
    """Add new sequence to database"""
    class Meta:  # lint:ok
        model = StringParameter
        fields = ['sentence', 'definitive', 'target_analyze']


class EditAnalystForm(ModelForm):
    "Form to edit analyst data of website"
    date_added = ''

    def __init__(self, *args, **kwargs):
        super(EditAnalystForm, self).__init__(*args, **kwargs)

    class Meta:
        model = ExtendWebsite
        exclude = ['website']


class EditAnalystDomainForm(ModelForm):
    "Form to edit analyst data of website"
    date_added = ''

    def __init__(self, *args, **kwargs):
        super(EditAnalystDomainForm, self).__init__(*args, **kwargs)

    class Meta:
        model = ExtendDomain
        exclude = ['domain']


class SearchForm(forms.Form):
    "search extendsomain by domain name"
    search = forms.CharField()

website_analyzer/views.py
"""views module for website_analyzer app."""
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required

from website_management.models import Website, Webpage, Domain
from website_analyzer.models import ExtendWebsite, StringParameter, \
                                    StringAnalysist, ExtendDomain
from website_analyzer.analyzer_lib import string_analyst, \
                                          add_list_url_to_webpage, \
                                          add_scam_url_website, \
                                          string_analysist, crawl_website
from website_analyzer.forms import AddScamWebsiteForm, AddSequenceForm, \
                                   EditAnalystForm, EditAnalystDomainForm, \
                                   SearchForm
from webscraper.pagescraper import PageScraper
from administrative.models import ClientSequence


@login_required
def add_sequence(request):
    """view to display and process form add new parameter sequence"""
    if request.user.is_staff:
        if request.method == 'POST':
            form = AddSequenceForm(request.POST)
            if form.is_valid():
                sentence = form.cleaned_data['sentence'].lower()
                target_analyze = form.cleaned_data['targer_analyze'].lower()
                definitive = form.cleaned_data['definitive']
                StringParameter.objects.create(sentence=sentence.strip(),
                                               target_analyze=target_analyze,
                                               definitive=definitive)
                return redirect('website_analyzer:view_sequence')
        else:
            form = AddSequenceForm()
        return render(request, 'website_analyzer/add_sequence.html',
                      {'form': form})
    else:
        return redirect('website_analyzer:analyst_dashboard')


@login_required
def analyze_website(request, hp_id):
    """Display page to analyze website,
    the last analysist result is displayed"""
    homepage = get_object_or_404(Website, id=hp_id)
    my_webpage = homepage.webpage_set.all()
    ExtendWebsite.objects.get_or_create(homepage=homepage)
    context = {'name': homepage.name,
               'id': homepage.id,
               'domain': homepage.domain.name,
               'domain_id': homepage.domain.id,
               'date_added': homepage.date_added,
               'scam': homepage.extendhomepage.scam,
               'inspection': homepage.extendhomepage.inspected,
               'report': homepage.extendhomepage.reported,
               'access': homepage.extendhomepage.access,
               'whitelist': homepage.extendhomepage.whitelist,
               'full_crawl': homepage.extendhomepage.full_crawled,
               'times_analyzed': homepage.extendhomepage.times_analyzed,
               'webpages': [],
               'params': []}
    for web in my_webpage:
        context['webpages'].append({'id': web.id, 'url': web.url})
    for item in StringAnalysist.objects.filter(webpage__in=my_webpage,
                                               find=True):
        temp = {'parameter': '', 'webpage': '', 'find': ''}
        temp['parameter'] = item.parameter.sentence
        temp['webpage'] = item.webpage.url
        temp['find'] = item.find
        temp['time'] = item.time
        context['params'].append(temp)
    return render(request, 'website_analyzer/analyze_website.html', context)


@login_required
def start_analyze(request, hp_id):
    """execute analyze process"""
    string_analyst(hp_id)
    return redirect('website_analyzer:analyze_website', hp_id=hp_id)


@login_required
def analyst_dashboard(request):
    """Display summary info of analyzed website."""
    exthp = ExtendWebsite.objects.all()
    context = {'scam_count': exthp.filter(scam=True).count(),
               'whitelist_count': exthp.filter(whitelist=True).count(),
               'hp_count': Website.objects.all().count()}
    return render(request, 'website_analyzer/dashboard.html', context)


@login_required
def edit_analyst(request, homepage_id):
    """Display edit form of analyst data for current homepage"""
    website = get_object_or_404(Website, id=homepage_id)
    exth = ExtendWebsite.objects.get(homepage=website)
    if request.method == 'POST':
        form = EditAnalystForm(request.POST)
    if form.is_valid():
        exth.scam = form.cleaned_data['scam']
        exth.inspected = form.cleaned_data['inspected']
        exth.reported = form.cleaned_data['reported']
        exth.access = form.cleaned_data['access']
        exth.whitelist = form.cleaned_data['whitelist']
        exth.save()
        website.save()
        return redirect('website_analyzer:analyze_website',
                        hp_id=website.id)
    else:
        form = EditAnalystForm()
    context = {'form': form,
               'homepage': {}}
    context['homepage'] = {'id': website.id,
                           'name': website.name,
                           'date_added': website.date_added,
                           'scam_status': website.extendhomepage.scam,
                           'inspected': website.extendhomepage.inspected,
                           'reported': website.extendhomepage.reported,
                           'access': website.extendhomepage.access,
                           'whitelist': website.extendhomepage.whitelist}
    return render(request, 'website_analyzer/edit_analyst.html', context)


@login_required
def extract_links(request, web_id):
    """extract links from the current webpage. filter ideal links only"""
    webpage = get_object_or_404(Webpage, id=web_id)
    page_scraper = PageScraper()
    links = page_scraper.ideal_urls(webpage.html_page)
    add_list_url_to_webpage(links)
    return redirect('website_management:view_all_webpages')


@login_required
def add_scam_website(request):
    """manually add website known as scam"""
    if request.user.is_staff:
        if request.method == 'POST':
            form = AddScamWebsiteForm(request.POST)
            if form.is_valid():
                add_scam_url_website(form.cleaned_data['url'])
                return redirect('website_analyzer:view_websites')
        else:
            form = AddScamWebsiteForm()
        return render(request, 'website_analyzer/add_scam_website.html',
                      {'form': form})
    else:
        return redirect('website_analyzer:analyst_dashboard')


@login_required
def view_websites(request):
    """display scam website"""
    form = SearchForm(request.GET)
    if form.is_valid():
        websites = Website.objects.filter(
            name__contains=form.cleaned_data['search']).values_list(
                'id', flat=True).order_by('id').reverse()
    else:
        websites = Website.objects.only(
            'id').all().values_list('id', flat=True).order_by('id').reverse()
    context = {'websites': websites, 'divided_websites': []}
    paginator = Paginator(context['websites'], 20)
    page = request.GET.get('page')
    try:
        context['pagebase'] = paginator.page(page)
    except PageNotAnInteger:
        context['pagebase'] = paginator.page(1)
    except EmptyPage:
        context['pagebase'] = paginator.page(paginator.num_pages)
    divided_websites = Website.objects.filter(
        id__in=context['pagebase'].object_list)
    context['searchbase'] = "Website name"
    if form.is_valid():
        for homepage in divided_websites.filter(
                name__contains=form.cleaned_data['search']):
            try:
                exthp = ExtendWebsite.objects.get(homepage=homepage)
                context['divided_websites'].append(
                    {'id': homepage.id,
                     'name': homepage.name,
                     'date_added': homepage.date_added,
                     'scam': exthp.scam,
                     'times_analyzed': exthp.times_analyzed,
                     'full_crawled': exthp.full_crawled,
                     'whitelist': exthp.whitelist,
                     'inspection': exthp.inspected,
                     'report': exthp.reported,
                     'access': exthp.access,
                     'web_count': homepage.webpage_set.all().count(),
                     'matched_sequence': {'min': 0, 'max': 0}})
            except ExtendWebsite.DoesNotExist:
                context['divided_websites'].append(
                    {'id': homepage.id,
                     'name': homepage.name,
                     'date_added': homepage.date_added,
                     'whitelist': 'n/a',
                     'scam': 'n/a',
                     'inspection': 'n/a',
                     'report': 'n/a',
                     'access': 'n/a',
                     'web_count': homepage.webpage_set.all().count(),
                     'matched_sequence': {'min': 0, 'max': 0}})
    else:
        for homepage in divided_websites:
            try:
                exthp = ExtendWebsite.objects.get(homepage=homepage)
                context['divided_websites'].append(
                    {'id': homepage.id,
                     'name': homepage.name,
                     'date_added': homepage.date_added,
                     'scam': exthp.scam,
                     'times_analyzed': exthp.times_analyzed,
                     'full_crawled': exthp.full_crawled,
                     'whitelist': exthp.whitelist,
                     'inspection': exthp.inspected,
                     'report': exthp.reported,
                     'access': exthp.access,
                     'web_count': homepage.webpage_set.all().count(),
                     'matched_sequence': {'min': 0, 'max': 0}})
            except ExtendWebsite.DoesNotExist:
                context['divided_websites'].append(
                    {'id': homepage.id,
                     'name': homepage.name,

website_analyzer/templates/website_analyzer/add_sequence.html
{% extends 'base.html' %}
{% block navigation %}
    {% include 'website_analyzer/analyst_nav.html' %}
{% endblock %}
{% block content-heading %}Add Sequence{% endblock %}
{% block content-body %}
    <form method="post" action="{% url 'website_analyzer:add_sequence' %}">
    {% csrf_token %}
        <table class="table table-bordered">
            {{ form.as_table }}
            <tr><td colspan="2">
                <input type="submit" value="Save new sequence" />
                <input type="reset" value="Clear input area" />
            </td></tr>
        </table>
    </form>
{% endblock %}

website_analyzer/templates/website_analyzer/analyst_domain_nav.html
<h4>Analyst Domain navigation</h4>
<ul>
    <li>
        <a href="{% url 'website_analyzer:view_analyst_domains' %}">
            View analyst domain
        </a>
    </li>
    <li>
        <a href="{% url 'website_analyzer:edit_analyst_domain' id %}">
            Edit analyst domain
        </a>
    </li>
</ul>

website_analyzer/templates/website_analyzer/analyst_nav.html
<div class="panel panel-primary">
    <div class="panel-heading">Analyst navigation</div>
    <div class="panel-body">
        <ul class="list-group">
            <li class="list-group-item">
                <a href="{% url 'website_analyzer:add_sequence' %}">
                    Add search keywords
                </a>
            </li>
            <li class="list-group-item">
                <a href="{% url 'website_analyzer:add_sequence' %}">
                    Add analytic parameter
                </a>
            </li>
            <li class="list-group-item">
                <a href="{% url 'website_management:view_all_keywords' %}">
                    View search keywords
                </a>
            </li>
            <li class="list-group-item">
                <a href="{% url 'website_analyzer:view_sequence' %}">
                    View analytic parameter
                </a>
            </li>
        </ul>
    </div>
</div>

website_analyzer/templates/website_analyzer/analyze_webpage.html
{% extends 'base.html' %}
{% block navigation %}
    {% include 'website_analyzer/analyst_nav.html' %}
    {% include 'website_analyzer/webpage_analyzer_nav.html' %}
{% endblock %}
{% block content %}
<h3>Analyze webpage</h3>
<table>
    <tr>
        <th align="left">Webpage url</th>
        <td><a href="{{ webpage.url }}" target="_blank">{{ webpage.url }}</a></td>
    </tr>
    <tr>
        <th align="left">Text body</th><td>{{ webpage.text_body }}</td>
    </tr>
    <tr>
        <th align="left">Word tokens</th>
        <td>
            {% for word in  webpage.word_tokens %}
            <div style="float: left;border:1px solid black;padding:3px;">
                {{ word }}</div> 
            {% empty %}
            Word tokens empty
            {% endfor %}
        </td>
    </tr>
</table>
{% endblock %}

website_analyzer/templates/website_analyzer/analyze_website.html
{% extends 'base.html' %}
{% block navigation %}
    {% include 'website_analyzer/analyst_nav.html' %}
    {% include 'website_analyzer/website_analyzer_nav.html' %}
{% endblock %}
{% block content %}
<h3>Analyze website</h3>
<table>
    {% if error_warning == "error" %}
        <tr>
            <th align="left"><strong>website ini mengandung informasi palsu</strong></th>
            <td><ul>{% for err in error_warning_msg %}
                    <li><strong>{{ err.parameter }}</strong></li>
                    {% endfor %}
            </ul></td>
        </tr>
    {% endif %}
    <tr>
        <th align="left">Homepage name</th><td>{{ name }}</td>
    </tr>
    <tr>
        <th align="left">Domain name</th><td>{{ domain }}</td>
    </tr>
    <tr>
        <th align="left">Date added</th><td>{{ date_added|date:"d M Y" }}</td>
    </tr>
    <tr>
        <th align="left">Inspection status</th><td>{{ inspection|yesno:"Inspected, Not Inspected, Unknown" }}</td>
    </tr>
    <tr>
        <th align="left">Scam status</th><td>{{ scam|yesno:"Yes, No, Unknown" }}</td>
    </tr>
    <tr>
        <th align="left">Report status</th><td>{{ report|yesno:"Reported, Not Reported, Unknown" }}</td>
    </tr>
    <tr>
        <th align="left">Access status</th><td>{{ access|yesno:"Accessible, Not Accessible, Unknown" }}</td>
    </tr>
    <tr>
        <th align="left">Whitelist status</th><td>{{ whitelist|yesno:"Yes, No, Unknown" }}</td>
    </tr>
    <tr>
        <th align="left">String analys result</th>
        <td>True = {{ string_analyst_result.tru }}<br />False = {{ string_analyst_result.fals }}<br />None = {{ string_analyst_result.non }}</td>
    </tr>
    <tr>
        <th align="left">String Analist duration</th><td>{{ duration }}</td>
    </tr>
    <tr>
        <th align="left">Average ratio compare</th><td>{{ average_ratio_compare }}</td>
    </tr>
    <tr>
        <th align="left">Ratio Analist duration</th><td>{{ ratio_duration }}</td>
    </tr>
        <th align="left">Times string analyzed</th><td>{{ times_string_analyzed }}</td>
    </tr>
    <tr>
        <th align="left">Times ratio analyzed</th><td>{{ times_ratio_analyzed }}</td>
    </tr>
    <tr>
        <th align="left">Full crawl</th><td>{{ full_crawl }}</td>
    </tr>
    <tr>
        <th align="left">Use As Parameter</th><td>{{ as_parameter }}</td>
    </tr>
    <tr>
        <th align="left" valign="top">List of webpages</th>
        <td>
            {% for web in webpages %}
                <a href="{% url 'website_analyzer:analyze_webpage' web.id %}"
                    title="{{ web.url }}">
                    {{ web.url|truncatechars:80 }}<br />
                </a>
            {% empty %}
                This website does not have webpages
            {% endfor %}
        </td>
    </tr>
    <tr>
        <th align="left">List of sequence</th>
        <td>
            {% for seq in params %}
            <div style="border:1px solid black;">
                <p>{{ seq.parameter }}</p>
                <p>{{ seq.webpage }}</p>
                <p>{{ seq.find }}</p>
                <p>{{ seq.time }}</p>
            </div>
            {% empty %}
                This website does not have matching sequence
            {% endfor %}
        </td>
    </tr>
    <tr>
        <th align="left">Ratio comparison</th>
        <td>
            {% for compare in webpage_compare_ratio %}
            <div style="border:1px solid black;">
                <p>{{ compare.parameter }}</p>
                <p>{{ compare.target }}</p>
                <p>{{ compare.ratio }}</p>
                <p>{{ compare.compare_time }}</p>
            </div>
            {% empty %}
                This website does not have comparison ratio data
            {% endfor %}
        </td>
    </tr>
</table>
{% endblock %}

website_analyzer/templates/website_analyzer/detail_analyst_domain.html
{% extends 'base.html' %}
{% block navigation %}
    {% include 'website_analyzer/analyst_nav.html' %}
    {% include 'website_analyzer/analyst_domain_nav.html' %}
{% endblock %}
{% block content %}
<h3>Detail Analyst Domain</h3>
<table>
    <tr>
        <th align="left">Domain name</th><td>{{ name }}</td>
    </tr>
    <tr>
        <th align="left">Date added</th><td>{{ date_added|date:"d M Y" }}</td>
    </tr>
    <tr>
        <th align="left">Free/Paid</th><td>{{ free|yesno:"Free, Paid, Unknown" }}</td>
    </tr>
    <tr>
        <th align="left">Whitelist status</th><td>{{ whitelist|yesno:"Yes, No, Unknown" }}</td>
    </tr>
    <tr>
        <th align="left" valign="top">List of homepages</th>
        <td>
            {% for hp in homepages %}
                <a href="{% url 'website_management:homepage_detail' hp.id %}"
                    title="{{ hp.name }}">
                    {{ hp.name|truncatechars:80 }}<br />
                </a>
            {% empty %}
                This Domain does not have homepages
            {% endfor %}
        </td>
    </tr>
</table>
{% endblock %}

website_analyzer/templates/website_analyzer/edit_analyst.html
{% extends 'base.html' %}
{% block navigation %}
    {% include 'website_analyzer/analyst_nav.html' %}
    {% include 'website_analyzer/website_analyzer_nav.html' %}
{% endblock %}
{% block content %}
<h3>Edit  website analyst data for: {{ homepage.name }}</h3>
<form action="{% url 'website_analyzer:edit_analyst' homepage.id %}"
      method="post">
{% csrf_token %}
<table>
    {{ form }}
</table>
<input type="submit" value="Save Edit" />
<a href="{% url 'website_analyzer:edit_analyst' homepage.id %}">
    Cancel edit and return
</a>
</form>
{% endblock %}

website_analyzer/templates/website_analyzer/edit_analyst_domain.html
{% extends 'base.html' %}
{% block navigation %}
    {% include 'website_analyzer/analyst_nav.html' %}
    {% include 'website_analyzer/analyst_domain_nav.html' %}
{% endblock %}
{% block content %}
<h3>Edit analyst domain data: {{ domain.name }}</h3>
<form action="" method="post">
{% csrf_token %}
<table>
    {{ form }}
</table>
<input type="submit" value="Save Edit" />
<a href="{% url 'website_analyzer:detail_analyst_domain' domain.id %}">
    Cancel edit and return
</a>
</form>
{% endblock %}

website_analyzer/templates/website_analyzer/search.html
    <h4>Page Navigation</h4>
<div class="pagination">
    <span class="step-links">
        {% if pagebase.has_previous %}
            {% if request.GET|length == 0 %}
            <a href="?page={{ pagebase.previous_page_number }}">previous</a>
            {% else %}
            <a href="{{ request.get_full_path }}&page={{ pagebase.previous_page_number }}">previous</a>
            {% endif %}
        {% endif %}

        <span class="current">
            Page {{ pagebase.number }} of {{ pagebase.paginator.num_pages }}.
        </span>

        {% if pagebase.has_next %}
            {% if request.GET|length == 0 %}
            <a href="?page={{ pagebase.next_page_number }}">next</a>
            {% else %}
            <a href="{{ request.get_full_path }}&page={{ pagebase.next_page_number }}">next</a>
            {% endif %}
        {% endif %}
    </span>
</div>

website_analyzer/templates/website_analyzer/view_analyst_domains.html
{% extends 'base.html' %}
{% block navigation %}
    {% include 'website_analyzer/analyst_nav.html' %}
    <form action="" method="get">
        {{ filter.form.as_p }}
        <br />
        <input type="submit" value="submit edit" />
    </form>
    {% include 'website_analyzer/search.html' %}
{% endblock %}
{% block content-heading %}View Analyst Domain{% endblock %}
{% block content-body %}
    <table class="table table-bordered">
        <tr>
            <th style="padding:3px;">No</th>
            <th style="padding:3px;">Domain
            <th style="padding:3px;">Date Added</th>
            <th style="padding:3px;">Whitelist</th>
            <th style="padding:3px;">Free</th>
            <th style="padding:3px;">Homepage<br />Count?</th>
            <th style="padding:3px;">Action</th>
        </tr>
        {% for dom in divided_domains %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><span title="{{ dom.name }}">{{ dom.name|truncatechars:25 }}</span></td>
            <td>{{ dom.date_added|date:"b d, Y" }}</td>
            <td>{{ dom.whitelist }}</td>
            <td>{{ dom.free }}</td>
            <td>{{ dom.hp_count }}</td>
            <td><a href="{% url 'website_analyzer:detail_analyst_domain' dom.id %}">Detail</a></td>
        </tr>
        {% empty %}
            Analyst Domain database is empty
        {% endfor %}
    </table>
{% endblock %}

website_analyzer/templates/website_analyzer/view_analyst_result.html
{% extends 'base.html' %}
{% block navigation %}
    {% include 'website_analyzer/analyst_nav.html' %}
    <h4>Page Navigation</h4>
<div class="pagination">
    <span class="step-links">
        {% if analyst_results.has_previous %}
            <a href="?page={{ analyst_results.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ analyst_results.number }} of {{ analyst_results.paginator.num_pages }}.
        </span>

        {% if analyst_results.has_next %}
            <a href="?page={{ analyst_results.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
{% endblock %}
{% block content-heading %}View Analyst Result{% endblock %}
{% block content-body %}
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Webpage</th>
            <th>Analyze Time</th>
            <th>String Parameter</th>
            <th>Find</th>
            <th>Analyze</th>
        </tr>
        {% for result in filtered_results %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'website_management:webpage_detail' result.webpage.id %}">
                    <span title="{{ result.webpage.url }}">
                        {{ result.webpage.url|truncatechars:60 }}</span></a></td>
            <td>{{ result.analyze_time|date:"H:i d-m-Y" }}</td>
            <td>{{ result.string_parameter }}</td>
            <td>{{ result.find }}</td>
            <td><a href="{% url 'website_analyzer:analyze_website' result.webpage.homepage_id %}">
                    Analyze</a></td>
        </tr>
        {% empty %}
            <td> - </td>
            <td> - </td>
            <td> - </td>
            <td> - </td>
            <td> - </td>
        {% endfor %}
    </table>
{% endblock %}

website_analyzer/templates/website_analyzer/view_sequences.html
{% extends 'base.html' %}
{% block navigation %}
    {% include 'website_analyzer/analyst_nav.html' %}
    <h4>Page Navigation</h4>
<div class="pagination">
    <span class="step-links">
        {% if parameters.has_previous %}
            <a href="?page={{ parameters.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ parameters.number }} of {{ parameters.paginator.num_pages }}.
        </span>

        {% if parameters.has_next %}
            <a href="?page={{ parameters.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
{% endblock %}
{% block content-heading %}View String parameters{% endblock %}
{% block content-body %}
    <table class="table table-bordered">
        <tr>
            <th>
               No.
            </th>
            <th>
               String parameter
            </th>
            <th>
               Definitive
            </th>
            <th>
               Date Added
            </th>
        </tr>
        {% for parameter in parameters %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ parameter.sentence }}</td>
                <td>{{ parameter.definitive }}</td>
                <td>{{ parameter.date_added }}</td>
            </tr>
        {% empty %}
            <tr>
                <td> - </td>
                <td> - </td>
                <td> - </td>
                <td> - </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}