ScamSearcher/urls.py
"""ROOT_URLCONF for ScamSearcher project."""
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from ScamSearcher.views import login, logout, welcome, user_profile, \
                               password_changed
from website_management.views import website_dashboard


urlpatterns = (
    url(r'^$', website_dashboard, name='welcome'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login$', login, name='login'),
    url(r'^logout$', logout, name='logout'),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^password_change/',
        auth_views.password_change,
        {'post_change_redirect': 'password_changed'},
        name='password_change'),
    url(r'^password_changed/$',
        password_changed,
        name='password_changed'),
    url(r'^$', welcome, name='welcome'),
    url(r'^profile/$', user_profile, name='user_profile'),

    url(r'^website_management/',
        include('website_management.urls',
                namespace='website_management',
                app_name='website_management')),
    url(r'^website_analyzer/',
        include('website_analyzer.urls',
                namespace='website_analyzer',
                app_name='website_analyzer')),
    url(r'^administrative/',
        include('administrative.urls',
                namespace='administrative',
                app_name='administrative')),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

administrative/urls.py
"""urls module for adminstrative app."""
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views


urlpatterns = [
    url(r'^$', views.admin_dashboard, name='admin_dashboard'),
    # client url section
    url(r'^add-client/$',
        views.add_client, name='add_client'),
    url(r'^view-client/$',
        views.view_client, name='view_client'),
    url(r'^edit-client/(?P<pk>\d+)/$',
        login_required(views.EditClient.as_view()), name='edit_client'),
    url(r'^delete-client/(?P<client_id>\d+)/$',
        views.delete_client, name='delete_client'),
    url(r'^delete-client-process/$',
        views.delete_client_process, name='delete_client_process'),
    url(r'^detail-client/(?P<client_id>\d+)/$',
        views.detail_client, name='detail_client'),
    url(r'^add-homepage/(?P<client_id>\d+)/$',
        views.add_homepage, name='add_homepage'),
    url(r'^delete-homepage/(?P<pk>\d+)/$',
        login_required(views.WebsiteDelete.as_view()),
        name='delete_homepage'),
    url(r'^delete-homepage-success/$',
        views.delete_homepage_success,
        name='delete_client_website_success'),
    url(r'^view-event/(?P<client_id>\d+)/$',
        views.view_event, name='view_event'),
    url(r'^add-event/(?P<client_id>\d+)/$',
        views.add_event, name='add_event'),
    url(r'^edit-event/(?P<pk>\d+)/$',
        login_required(views.EditEvent.as_view()),
        name='edit_event'),
    url(r'^delete-event/(?P<event_id>\d+)/$',
        views.delete_event, name='delete_event'),
    url(r'^delete-event-process/$',
        views.delete_event_process, name='delete_event_process'),
    url(r'^detail-event/(?P<event_id>\d+)/$',
        views.detail_event, name='detail_event'),
    url(r'^view-client-keyword/(?P<client_id>\d+)/$',
        views.view_client_keyword, name='view_client_keyword'),
    url(r'^add-client-keyword/(?P<client_id>\d+)/$',
        views.add_client_keyword, name='add_client_keyword'),
    url(r'^view-client-sequence/(?P<client_id>\d+)/$',
        views.view_client_sequence, name='view_client_sequence'),
    url(r'^add-client-sequence/(?P<client_id>\d+)/$',
        views.add_client_sequence, name='add_client_sequence'),

    # operator url section
    url(r'^add-operator/(?P<client_id>\d+)/$',
        views.add_operator, name='add_operator'),
    url(r'^view-operator/(?P<client_id>\d+)/$',
        views.view_operator, name='view_operator'),
    url(r'^edit-operator/(?P<operator_id>\d+)/$',
        views.edit_operator, name='edit_operator'),
    url(r'^edit-operator-process/$',
        views.edit_operator_process, name='edit_operator_process'),
    url(r'^delete-operator/(?P<operator_id>\d+)/$',
        views.delete_operator, name='delete_operator'),
    url(r'^delete-operator-process/$',
        views.delete_operator_process, name='delete_operator_process'),

    # user url section
    url(r'^add-user/$', views.add_user, name='add_user'),
    url(r'^view-user/$',
        views.view_user, name='view_user'),
    url(r'^edit-user/(?P<pk>\d+)/$',
        login_required(views.EditUser.as_view()),
        name='edit_user'),
    url(r'^delete-user/(?P<pk>\d+)/$',
        login_required(views.DeleteUser.as_view()),
        name='delete_user'),

    # event url section
    url(r'^view-all-event/$',
        views.view_all_event, name='view_all_event'),
    url(r'^view-sent-mail/$',
        views.view_sent_mail,
        name='view_sent_mail'),
    ]

website_management/urls.py
"""urls module for website_management app."""
from django.conf.urls import url

from website_management import views


urlpatterns = [
    url(r'^$', views.website_dashboard,
        name='website_dashboard'),
    url(r'^homepage_detail/(?P<hp_id>\d+)/$',
        views.homepage_detail, name='homepage_detail'),
    url(r'^view_all_homepages/$',
        views.view_all_homepages, name='view_all_homepages'),
    url(r'^view_all_keywords/$',
        views.view_all_keywords, name='view_all_keywords'),
]

administrative/views.py
"""views module for administrative app."""
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic.edit import DeleteView, UpdateView
from django.core.urlresolvers import reverse_lazy

from administrative.models import Client, Event, Operator, Website, \
                                  ClientKeyword, ClientSequence
from administrative.form import AddClientForm, AddClientHomepageForm, \
                                DeleteClientForm, AddEventForm, \
                                DeleteEventForm, AddOperatorForm, \
                                AddUserForm, AddClientKeywordForm, \
                                AddClientSequenceForm
from administrative.administrative_lib import save_client
from website_management.management_lib import add_url_to_webpage
from website_management.models import Webpage
from website_analyzer.models import StringParameter, SearchKeywords


@login_required
def admin_dashboard(request):
    "Display summary administrative info"
    if request.user.is_staff:
        context = {}
        clients = Client.objects.all().order_by('date_start')
        operators = Operator.objects.all().order_by('date_start')
        events = Event.objects.all().order_by('time_start')
        context['clients'] = {'count': clients.count(), 'last_added': []}
        for client in clients[:5]:
            client_data = {'id': client.id, 'name': client.name}
            context['clients']['last_added'].append(client_data)
        context['operators'] = {'count': operators.count(), 'last_added': []}
        for operator in operators[:5]:
            operator_data = {'name': operator.user.get_username()}
            context['operators']['last_added'].append(operator_data)
        context['events'] = {'count': events.count(), 'last_added': []}
        for event in events[:5]:
            event_data = {'id': event.id, 'name': event.name}
            context['events']['last_added'].append(event_data)
        return render(request, 'administrative/dashboard.html', context)
    else:
        operator = Operator.objects.get(user=request.user)
        client = operator.client
        return redirect('administrative:detail_client', client.id)


@login_required
def add_client(request):
    'Display add client form'
    if request.method == 'POST':
        form = AddClientForm(request.POST)
        if form.is_valid():
            save_client(name=form.cleaned_data['name'],
                        email=form.cleaned_data['email'],
                        phone=form.cleaned_data['phone'],
                        address=form.cleaned_data['address'])
            return redirect('administrative:view_client')
    else:
        form = AddClientForm()
    return render(request, 'administrative/add_client.html', {'form': form})


@login_required
def view_client(request):
    'Display all client'
    clients = Client.objects.all().order_by('date_start').reverse()
    context = {'clients': []}
    for item in clients:
        client_data = {'id': item.id,
                       'name': item.name,
                       'email': item.email,
                       'phone': item.phone,
                       'status': '',
                       'address': item.address}
        if item.date_end is None:
            client_data['status'] = 'Active'
        else:
            client_data['status'] = 'Not Active'
        context['clients'].append(client_data)
    paginator = Paginator(context['clients'], 10)
    page = request.GET.get('page')
    try:
        context['clients'] = paginator.page(page)
    except PageNotAnInteger:
        context['clients'] = paginator.page(1)
    except EmptyPage:
        context['clients'] = paginator.page(paginator.num_pages)
    return render(request, 'administrative/view_client.html', context)


@login_required
def detail_client(request, client_id):
    "Display detail client's data"
    client = get_object_or_404(Client, id=client_id)
    client_data = {'id': client.id,
                   'name': client.name,
                   'email': client.email,
                   'phone': client.phone,
                   'date_start': client.date_start,
                   'date_end': client.date_end,
                   'status': '',
                   'websites': [],
                   'address': client.address}
    if client_data['date_end'] is None:
        client_data['status'] = 'Active'
    else:
        client_data['status'] = 'Not Active'
    websites = Website.objects.filter(client=client)
    for website in websites:
        client_data['websites'].append({'url': website.homepage.name,
                                        'id_homepage': website.homepage.id,
                                        'id_website': website.id})
    return render(request,
                  'administrative/detail_client.html',
                  {'client': client_data})


@login_required
def add_homepage(request, client_id):
    "Display add client's homepage form"
    client = Client.objects.get(id=client_id)
    if request.method == 'POST':
        form = AddClientHomepageForm(request.POST)
        if form.is_valid():
            if Webpage.objects.filter(url=form.cleaned_data['url']).exists():
                webpage = Webpage.objects.get(url=form.cleaned_data['url'])
            else:
                add_url_to_webpage(form.cleaned_data['url'])
            webpage = Webpage.objects.get(url=form.cleaned_data['url'])
            try:
                Website.objects.create(client=form.cleaned_data['client'],
                                       homepage=webpage.homepage,
                                       event=form.cleaned_data['event'])
                return redirect('administrative:detail_client',
                                client_id=client_id)
            except:
                return redirect('administrative:detail_client',
                                client_id=client_id)
    else:
        form = AddClientHomepageForm(initial={'client': client, 'event': None})
        form.fields['event'].queryset = Event.objects.filter(client=client)
    return render(request,
                  'administrative/add_homepage.html',
                  {'form': form,
                   'client': {'id': client.id,
                              'name': client.name}})


class WebsiteDelete(DeleteView):
    "delete client's website"
    model = Website
    success_url = reverse_lazy('administrative:delete_client_website_success')
    template_name = 'administrative/delete_client_website.html'


@login_required
def delete_homepage_success(request):
    "display delete success"
    return render(request, 'administrative/delete_client_website_success.html')


class EditClient(UpdateView):
    'Display edit client form'
    model = Client
    success_url = reverse_lazy('administrative:view_client')
    fields = ['name', 'email', 'phone', 'address']
    template_name_suffix = '_edit_form'


@login_required
def delete_client(request, client_id):
    'function to set date_end value (delete) to client'
    client = Client.objects.get(id=client_id)
    form = DeleteClientForm()
    return render(request,
                  'administrative/delete_client.html',
                  {'form': form,
                   'client': {'id': client.id,
                              'name': client.name}})


@login_required
def delete_client_process(request):
    "processing delete client (saving date_end)"
    client = get_object_or_404(Client, id=request.POST['id_client'])
    if request.POST['status'] == "deactive":
        client.date_end = timezone.now()
        client.save()
    elif request.POST['status'] == "active":
        client.date_end = None
        client.save()
    else:
        pass
    return redirect('administrative:detail_client', client.id)


@login_required
def add_operator(request, client_id):
    """Add client's operator."""
    client = Client.objects.get(id=client_id)
    if request.method == 'POST':
        form = AddOperatorForm(request.POST)
        if form.is_valid():
            uname = form.cleaned_data['username']
            passwd = form.cleaned_data['password']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            client = form.cleaned_data['client']
            user = User.objects.create_user(username=uname,
                                            password=passwd,
                                            email=email,
                                            first_name=first_name,
                                            last_name=last_name,)
            Operator.objects.create(client=client, user=user)
            return redirect('administrative:view_operator', client.id)
    else:
        form = AddOperatorForm(initial={'client': client})
    return render(request,
                  'administrative/add_operator.html',
                  {'form': form,
                   'client': {'id': client.id, 'name': client.name}})


def view_operator(request, client_id):
    'Display all operator form'
    client = get_object_or_404(Client, id=client_id)
    operators = Operator.objects.filter(client=client)
    context = {'operators': [],
               'client': {'id': client.id, 'name': client.name}}
    for operator in operators:
        operator_data = {'username': operator.user.get_username(),
                         'id': operator.id,
                         'fullname': operator.user.get_full_name(),
                         'email': operator.user.email,
                         'status': '',
                         'time_start': operator.date_start,
                         'time_end': operator.date_end}
        if operator.user.is_active:

administrative/templates/administrative/add_client_sequence.html
{% extends 'base.html' %}
{% block navigation %}
    {% include 'administrative/admin_nav.html' %}
    {% include 'administrative/client_detail_nav.html' %}    
{% endblock %}
{% block pagetitle %}Add new cient sequence| ScamSearcher{% endblock %}
{% block content %}
<h3>Add new sequence for {{ client.name }}</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="" method="post">
{% csrf_token %}
{{ form.as_p }}
<br />
<br />
<input type="submit" value="Save new sequence" />
<input type="reset" value="Clear input area" />
</form>
{% endblock %}

administrative/templates/administrative/add_event.html
{% extends 'base.html' %}
{% block navigation %}
    {% include 'administrative/admin_nav.html' %}
    {% include 'administrative/client_detail_nav.html' %}    
{% endblock %}
{% block pagetitle %}Add new event for client | ScamSearcher{% endblock %}
{% block content %}
<h3>Add new event for {{ client.name }}</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'administrative:add_event' client.id %}" method="post">
{% csrf_token %}
{{ form.as_p }}
<br />
<br />
<input type="submit" value="Save new event" />
<input type="reset" value="Clear input area" />
</form>
{% endblock %}

administrative/templates/administrative/add_operator.html
{% extends 'base.html' %}
{% block navigation %}
    {% include 'administrative/admin_nav.html' %}
    {% include 'administrative/client_detail_nav.html' %}{% endblock %}
{% block pagetitle %}Add new operator | ScamSearcher{% endblock %}
{% block content %}
<h3>Add new operator for {{ client.name }}</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'administrative:add_operator' client.id %}" method="post">
{% csrf_token %}
{{ form.as_p }}
<br />
<input type="submit" value="Add new operator" />
<input type="reset" value="Clear input area" />
</form>
{% endblock %}

administrative/templates/administrative/add_user.html
{% extends 'base.html' %}
{% block navigation %}{% include 'administrative/admin_nav.html' %}{% endblock %}
{% block pagetitle %}Tambah user baru | ScamSearcher{% endblock %}
{% block content %}
<h3>Tambah user baru</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'administrative:add_user' %}" method="post">
{% csrf_token %}
{{ form.as_p }}
<br />
<br />
<input type="submit" value="Simpan data user" />
<input type="reset" value="Bersihkan area input" />
</form>
{% endblock %}

administrative/templates/administrative/client_detail_nav.html
<h4>Client detail navigation</h4>
<ul>
    <li><a href="{% url 'administrative:detail_client' client.id %}">
            Detail
        </a></li>
    <li><a href="{% url 'administrative:add_homepage' client.id %}">
            Add homepage</a></li>
    <li><a href="{% url 'administrative:edit_client' pk=client.id %}">
            Edit client</a></li>
    <li><a href="{% url 'administrative:delete_client' client.id %}">
            Delete client</a></li>
    <li><a href="{% url 'administrative:add_event' client.id %}">
            Add event</a></li>
    <li><a href="{% url 'administrative:view_event' client.id %}">
            View event</a></li>
    <li><a href="{% url 'administrative:add_operator' client.id %}">
            Add operator </a></li>
    <li><a href="{% url 'administrative:view_operator' client.id %}">
            View Operator</a></li>
    <li><a href="{% url 'administrative:add_client_keyword' client.id %}">
            Add client keyword</a></li>
    <li><a href="{% url 'administrative:view_client_keyword' client.id %}">
            View client keyword</a></li>
    <li><a href="{% url 'administrative:add_client_sequence' client.id %}">
            Add client sequence</a></li>
    <li><a href="{% url 'administrative:view_client_sequence' client.id %}">
            View client sequence</a></li>
</ul>

administrative/templates/administrative/client_edit_form.html
{% extends 'base.html' %}
{% block navigation %}
{% include 'administrative/admin_nav.html' %}
{% include 'administrative/client_detail_nav.html' %}
{% endblock %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save Edit" />
</form>
{% endblock %}

administrative/templates/administrative/dashboard.html
{% extends 'base.html' %}
{% block navigation %}
{% include 'administrative/admin_nav.html' %}
{% endblock %}
{% block content %}
<h3>Rangkuman informasi administratif</h3>
<table>
    <tr>
        <th align="left">Jumlah Operator</th><td>{{ operators.count|default:'0' }}</td>
    </tr>
    <tr>
        <th align="left">Jumlah Klien</th><td>{{ clients.count|default:'0' }}</td>
    </tr>
    <tr>
        <th align="left">Jumlah Even</th><td>{{ events.count|default:'0' }}</td>
    </tr>
</table>
<br />
<table>
    <tr><th>Operator terbaru</th></tr>
    {% for opt in operators.last_added %}
    <tr>
        <td>{{ opt.name }}</td>
    </tr>
    {% empty %}
    <tr><td>Data operator kosong</td></tr>
    {% endfor %}
</table>

<br />
<table>
    <tr><th>Klien terbaru</th></tr>
    {% for client in clients.last_added %}
    <tr>
        <td>
            <a href="{% url 'administrative:detail_client' client.id %}">
                {{ client.name }}
            </a>
        </td>
    </tr>
    {% empty %}
    <tr><td>Data klien kosong</td></tr>
    {% endfor %}
</table>

<br />
<table>
    <tr><th>Even terbaru</th></tr>
    {% for event in events.last_added %}
    <tr>
        <td>
            <a href="{% url 'administrative:detail_event' event.id %}">
                {{ event.name }}
            </a>
        </td>
    </tr>
    {% empty %}
    <tr><td>Data even kosong</td></tr>
    {% endfor %}
</table>
{% endblock %}

administrative/templates/administrative/delete_client.html
{% extends 'base.html' %}
{% block navigation %}
    {% include 'administrative/admin_nav.html' %}
    {% include 'administrative/client_detail_nav.html' %}{% endblock %}
{% block pagetitle %}Delete client | ScamSearcher{% endblock %}
{% block content %}
<h3>Delete client: {{ client.name }}</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'administrative:delete_client_process' %}" method="post">
{% csrf_token %}
Change Status: <input type="radio" name="status" value="deactive" /> Deactive <input type="radio" name="status" value="active" checked/> Active
<input type="hidden" name="id_client" value="{{ client.id }}" />
<br />
<br />
<input type="submit" value="Save new client's status" />
<input type="reset" value="Clear input area" />
</form>
{% endblock %}

administrative/templates/administrative/delete_client_website.html
{% extends 'base.html' %}
{% block navigation %}
    {% include 'administrative/admin_nav.html' %}
{% endblock %}
{% block pagetitle %}Delete client's homepage | ScamSearcher{% endblock %}
{% block content %}
<h3>Delete confirmation</h3>
Are you sure you want to delete {{ object }}?
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, I'm sure.</button>
</form>
{% endblock %}

administrative/templates/administrative/detail_client.html
{% extends 'base.html' %}
{% block navigation %}
{% include 'administrative/admin_nav.html' %}
{% include 'administrative/client_detail_nav.html' %}
{% endblock %}
{% block content %}
<h3>Client detail: {{ client.name }}</h3>
<table>
    <tr>
        <th align="left">Status</th>
        <td>{{ client.status }}</td>
    </tr>
    <tr>
        <th align="left">Name</th>
        <td>{{ client.name }}</td>
    </tr>
    <tr>
        <th align="left">Email</th>
        <td>{{ client.email }}</td>
    </tr>
    <tr>
        <th align="left">Phone</th>
        <td>{{ client.phone }}</td>
    </tr>
    <tr>
        <th align="left">Date added</th>
        <td>{{ client.date_start }}</td>
    </tr>
    <tr>
        <th align="left">Date ended</th>
        <td>{{ client.date_end }}</td>
    </tr>
    <tr>
        <th align="left">Address</th>
        <td>{{ client.address }}</td>
    </tr>
    <tr>
        <th align="left">Websites</th>
        <td>
        <ul>
        {% for web in client.websites %}
            <li><a href="{% url 'website_management:homepage_detail' web.id_homepage %}">
                {{ web.url }}</a> (<a href="{% url 'administrative:delete_homepage' pk=web.id_website %}">Delete</a>)
            </li>
        {% empty %}
            No homepage database for this client
        {% endfor %}
        </ul>
        </td>
    </tr>
</table>
{% endblock %}

administrative/templates/administrative/edit_operator.html
{% extends 'base.html' %}
{% block navigation %}
{% include 'administrative/admin_nav.html' %}
{% include 'administrative/client_detail_nav.html' %}
{% endblock %}
{% block content %}
<h3>Edit operator</h3>
<form method="post" action="{% url 'administrative:edit_operator_process' %}">{% csrf_token %}
<input type="hidden" name="operator_id" value="{{ operator.id }}" />
<table>
<tr><td>Username</td><td>{{ operator.username }}</td></tr>
<tr><td>First Name</td><td><input type="text" name="first_name" value="{{ operator.first_name }}" /></td></tr>
<tr><td>Last Name</td><td><input type="text" name="last_name" value="{{ operator.last_name }}" /></td></tr>
<tr><td>email</td><td><input type="text" name="email" value="{{ operator.email }}" /></td></tr>
<tr><td colspan="2"><input type="submit" value="Save Operator Edit"> &nbsp;&nbsp;&nbsp;</td></tr>
</table>
</form>
{% endblock %}

administrative/templates/administrative/operator_edit_form.html
{% extends 'base.html' %}
{% block navigation %}
{% include 'administrative/admin_nav.html' %}
{% include 'administrative/client_detail_nav.html' %}
{% endblock %}
{% block content %}
<h3>Edit operator</h3>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save Edit" />
</form>
{% endblock %}

administrative/templates/administrative/user_update_form.html
{% extends 'base.html' %}
{% block navigation %}
{% include 'administrative/admin_nav.html' %}
{% endblock %}
{% block content %}
<h3>Edit user: {{ object.username }}</h3>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save Edit" />
</form>
{% endblock %}

administrative/templates/administrative/view_client_sequence.html
{% extends 'base.html' %}
{% block pagetitle %}View client's sequence | ScamSearcher{% endblock %}
{% block navigation %}
    {% include 'administrative/admin_nav.html' %}
    {% include 'administrative/client_detail_nav.html' %}
    <h4>Page navigation</h4>
    <div class="pagination">
        <span class="step-links">
            {% if sequences.has_previous %}
                <a href="?page={{ sequences.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ sequences.number }} of {{ sequences.paginator.num_pages }}.
            </span>

            {% if sequences.has_next %}
                <a href="?page={{ sequences.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
{% endblock %}
{% block content %}
<h3>Sequences belong to: <a href="{% url 'administrative:detail_client' client.id %}" />{{ client.name }}</a></h3>
{{ error_message }}
<table>
    <tr>
        <th>No.</th>
        <th>Sequence</th>
        <th>Event</th>
        <th>Definitive</th>
    </tr>
    {% for sequence in sequences %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ sequence.name }}</td>
            <td>{{ sequence.event }}</td>
            <td>{{ sequence.definitive }}</td>
        </tr>
    {% empty %}
        <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
        </tr>
    {% endfor %}
</table>
{% endblock %}